### ISSUE TITLE
Zrok Tunnel

### ISSUE THREAD

**Issue by Whyxeo** [anxety-solo/sd-webui-anxety-colab#10]
Trying to lauch from Zrok
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
~/content/file_cell/launch_en.py in <module>
     64 if zrok_token:
     65     get_ipython().system('zrok enable {zrok_token} &> /dev/null')
---> 66     tunnel.add_tunnel(command="zrok share public http://localhost:{port}/ --headless", name="zrok", pattern=re.compile(r"[\w-]+\.share\.zrok\.io"))
     67 # ======================== TUNNEL ========================
     68 

NameError: name 'tunnel' is not defined
![2024-04-12_222947](https://github.com/anxety-solo/sd-webui-notebook/assets/96664249/526c03af-4e89-49eb-b547-0046694d0004)

**Comment by anxety-solo** [comment]
At first I thought it was strange to get this error, but after checking I realized that it won't work in **sagemaker**.. If you are using that environment, I have removed the option to use it there for now. (I lost access to this environment and can't do tests, that's why I removed it.), and it's more profitable to use kaggle/colab :p

**Comment by DwyaneSkala** [comment]
> At first I thought it was strange to get this error, but after checking I realized that it won't work in **sagemaker**.. If you are using that environment, I have removed the option to use it there for now. (I lost access to this environment and can't do tests, that's why I removed it.), and it's more profitable to use kaggle/colab :p

Увидел что ты на русском разговариваешь, сначала не заметил.
Мы с женой используем Sagemaker потому что там можно nsfw рисовать без опаски, kaggle для этого не подходит и Colab не работает больше на Free тире, для нас это не вариант.
Поэтому надеялся на fix проблемы с sagemaker блокнотом

**Comment by anxety-solo** [comment]
Вы можете использовать nsfw как в kaggle, так и в colab. Бесплатная версия Colab также работает.
