### ISSUE TITLE
Missing PNGinfo

### ISSUE THREAD

**Issue by SonicSaber** [anxety-solo/sd-webui-anxety-colab#12]
where is the PNGinfo Tab?
can you at least add this extension instead? https://github.com/NoCrypt/sd-fast-pnginfo
it is faster than regular PNGinfo tab

**Comment by anxety-solo** [comment]
_This tab has been removed by me for its 'uselessness' as I find it easier to do this in other ways._
But if it is more convenient for you, I have installed this extension.

**Comment by SonicSaber** [comment]
> _This tab has been removed by me for its 'uselessness' as I find it easier to do this in other ways._ But if it is more convenient for you, I have installed this extension.

thank you very much!
I don't know about that other ways
