### ISSUE TITLE
Possibility of using two T4 gpus in Kaggle

### ISSUE THREAD

**Issue by DA21S321D** [anxety-solo/sd-webui-anxety-colab#9]
Admiration of your excellent work, since kaggle have the free source for two T4 gpus. How can i use them both?
![image](https://github.com/anxety-solo/sd-webui-notebook/assets/56549016/ac203563-d3d8-441e-8e22-dda8832326ef)

**Comment by anxety-solo** [comment]
Well, as I know, then: sd-webui does not support the use of multiple GPUs 💀(_Supported, but not how we want it.._)
